local plugins = require("plugins")
require("lazy").setup(plugins)

require("options")
require("keymap")
require("autocmd")

require("plugins.configs.cmp")
require("plugins.configs.lspconfig")
require("plugins.configs.rust-tools")
require("plugins.configs.dap")
require("plugins.configs.dapui")
require("plugins.configs.overseer")
require("plugins.configs.telescope")
require("plugins.configs.alpha")
--require("plugins.configs.which-key")
require("plugins.configs.edgy")
require("plugins.configs.oil")
require("plugins.configs.copilot")
require("plugins.configs.lualine")
