# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.45.1"
"plenary.nvim" = "scm"
"rocks-git.nvim" = "2.5.4"
nvim-dap = "0.10.0"
nvim-dap-ui = "4.0.0"
"tokyonight.nvim" = "4.11.0"
tree-sitter-rust = "0.0.50"
"mason.nvim" = "2.0.1"
rustaceanvim = "6.7.0"
"mason-lspconfig.nvim" = "2.1.0"
nvim-lspconfig = "2.4.0"
"nvim-tree.lua" = "1.6.0"
cmp-nvim-lsp = "scm"
"telescope.nvim"= "scm"
"obsidian.nvim" = "3.13.1"
"trouble.nvim" = "3.7.1"
"vgit.nvim" = "1.0.6"
